version: '3'

services:
  webcam_test:
    build: .
    image: webcam_test:latest
    command: python3 /webcam_test/webcam.py
    network_mode: "host"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - /home/vagrant/webcam_test:/webcam_test
    environment:
      DISPLAY: $DISPLAY